apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock-predictor
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/your-username/stock-predictor.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

